version: "3.9"

services:
  nestjs:
    container_name: nestjs
    build: ./requirements/nestjs
    image: nestjs
    env_file: .env
    depends_on:
      - postgresql
    ports:
      - 3000:3000
    networks:
      - transcendence
    volumes:
      - ./back:/var/www/html/back
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    image: postgres
    networks:
      - transcendence
    environment:
      POSTGRES_PASSWORD: toto
      POSTGRES_USER: toto
      POSTGRES_DB: transcendence
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  transcendence:
    name: transcendence
    driver: bridge
