version: "3.9"

volumes:
  back:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./srcs/back
  front:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./srcs/front
    
services:
  nestjs:
    container_name: nestjs
    build: ./srcs/requirements/nestjs
    image: nestjs
    env_file: ./srcs/.env
    depends_on:
      - postgresql
    ports:
      - 3000:3000
    networks:
      - transcendence
    volumes:
      - back:/var/www/html/back
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    image: postgres
    networks:
      - transcendence
    environment:
      POSTGRES_PASSWORD: toto
      POSTGRES_USER: toto
      POSTGRES_DB: transcendence
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  transcendence:
    name: transcendence
    driver: bridge
